### ISSUE TITLE
Cannot find class?

### ISSUE THREAD

**Issue by techn0guy** [saintsystems/nova-resource-group-menu#1]
Hello,

I've followed the instructions exactly and now none of the pages will load. It looks like an error is being thrown: 

Class &#039;Str&#039; not found (View: /Applications/MAMP/htdocs/crystal-council/vendor/saintsystems/nova-resource-group-menu/resources/views/navigation.blade.php)

**Comment by anderly** [comment]
@techn0guy what version of Laravel are running? It might be that the Illuminate\Support\Str helper is not imported by default.

**Comment by techn0guy** [comment]
I'm currently running 5.7

**Comment by techn0guy** [comment]
Is Illuminate\Support\Str normally imported by default?

**Comment by anderly** [comment]
It is in 5.8. I just pushed an update (0.0.8) to quality it. Try updating to that and let me know if you get past the error.

**Comment by techn0guy** [comment]
Thanks! But it still doesn't work. I was able to get it to work by explicitly putting `\Illuminate\Support\Str`. Although now I can see the menu link, but when I click it there is a console error:
TypeError: Cannot read property 'group' of undefined

I think I'm just going to upgrade Laravel to see if it fixes most of my problems.

**Comment by anderly** [comment]
@techn0guy do you have group names defined on your resources that you want to appear in the resource group menu?

**Comment by anderly** [comment]
@techn0guy just pushed 0.0.9 and switched references to `\Illuminate\Support\Str`

**Comment by techn0guy** [comment]
Yes, I pasted exactly what the setup guide had:
`public static $displayInNavigation = false;
    public static $group = 'Master Data';
    public static $subGroup = 'Vendors';`

**Comment by anderly** [comment]
@techn0guy ok, can you copy the error from the console and place here for reference?

**Comment by techn0guy** [comment]
See Below:
vendor.js?id=b30263b2f9d68433c3ce:1 TypeError: Cannot read property 'group' of undefined
    at a.group (resource-group-menu:686)
    at Ne.I3G/.Ne.get (vendor.js?id=b30263b2f9d68433c3ce:1)
    at Ne.I3G/.Ne.evaluate (vendor.js?id=b30263b2f9d68433c3ce:1)
    at a.group (vendor.js?id=b30263b2f9d68433c3ce:1)
    at a.render (resource-group-menu:731)
    at a.I3G/.t._render (vendor.js?id=b30263b2f9d68433c3ce:1)
    at a.n (vendor.js?id=b30263b2f9d68433c3ce:1)
    at Ne.I3G/.Ne.get (vendor.js?id=b30263b2f9d68433c3ce:1)
    at new Ne (vendor.js?id=b30263b2f9d68433c3ce:1)
    at vendor.js?id=b30263b2f9d68433c3ce:1

**Comment by anderly** [comment]
@techn0guy ok, thanks. I'm testing with a fresh nova project to track it down.

**Comment by anderly** [comment]
@techn0guy just tested on a fresh laravel install and fresh nova 2.0 install and wasn't able to reproduce.

Can you try one more time with version `0.0.10`?

**Comment by anderly** [comment]
@techn0guy let me know if you were able to get past this or if you updated to Nova 2.x

**Comment by anderly** [comment]
Closing due to inactivity.
